sudo: false
notifications:
  email: false
language: node_js
node_js:
  - 8
  - 7
  - 6
before_install:
  - npm i -g npm@latest
install:
  - npm i
jobs:
  include:
    - stage: test:coverage
      script:
        - npm run test:node
        - npm run test:coverage:check
      after_success:
        - npm run test:coverage:report
    - stage: test:browser
      after_script:
        - npm run test:browser:saucelabs
script:
  - npm run build:prod
  - npm run test:node
