name: Continous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build using Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 6, 10, 14 ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up environment
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Build with Node
      run: npm run build:prod
  test:
    name: Test using Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 6, 10, 14 ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Lint with ESLint
      run: npm run lint
    - name: Test with Node
      run: npm run test:node
    - name: Check coverage
      run: npm run test:coverage:check
    - name: Upload coverage to Coveralls
      run: npm run test:coverage:report
      env:
        COVERALLS_REPO_TOKEN: "${{ secrets.COVERALLS_REPO_TOKEN }}"
        COVERALLS_GIT_BRANCH: "${{ github.ref }}"
